import { generalTheme, frenchTheme } from "./modules/themes";
generalTheme();
//frenchTheme();
import { systemMaps } from "./SystemMaps/maps";
import { kevinCrudeProduction } from "./Kevin/crude_production/crude_production";
import { kevinCrudeExports } from "./Kevin/crude_exports/crude_exports";
import { kevinUsImports } from "./Kevin/us_imports/us_imports";
import { kevinCrudePrices } from "./Kevin/crude_prices/crude_prices";
import { coletteCrudeByRail } from "./Colette/crude_by_rail/crude_by_rail";
import { coletteMarine } from "./Colette/marine_exports/marine_exports";
import { coletteCrudeTakeaway } from "./Colette/crude_takeaway/crude_takeaway";
import { coletteCrudeMode } from "./Colette/crude_export_mode/crude_export_mode";
import { saraGasTraffic } from "./Sara/gas_traffic/gas_traffic";
import { sara2019 } from "./Sara/gas_2019/gas_2019";
import { saraMnp } from "./Sara/st_stephen/st_stephen";
import { rebeccaGasPrices } from "./Rebecca/gas_prices/gas_prices";
import { rebeccaGasProd } from "./Rebecca/gas_production/gas_production";
import { rebeccaGasTrade } from "./Rebecca/gas_trade/gas_trade";
import { cassandraAllPipes } from "./Cassandra/all_pipes/pipeline_metrics";
import { cassandraTolls } from "./Cassandra/tolls/tolls";
import { cassandraSettlements } from "./Cassandra/negotiated_settlements/settlements";
import { ryanNglProduction } from "./Ryan/ngl_production/ngl_production";
import { ryanNglExports } from "./Ryan/ngl_exports/ngl_exports";
import { jenniferFinResources } from "./Jennifer/financial_instruments/fin_resource";
import { jenniferRatingsMulti } from "./Jennifer/credit_ratings/creditRatingsMultiple";
import { jenniferRatingsCross } from "./Jennifer/credit_ratings_cross_section/credit_ratings_cross";
import { jenniferAbandonment } from "./Jennifer/abandonment_funding/abandonment";

systemMaps();
kevinCrudeProduction();
kevinCrudeExports();
kevinUsImports();
kevinCrudePrices();
coletteCrudeByRail();
coletteMarine();
coletteCrudeTakeaway();
coletteCrudeMode();
saraGasTraffic();
sara2019();
saraMnp();
rebeccaGasPrices();
rebeccaGasProd();
rebeccaGasTrade();
cassandraAllPipes();
cassandraTolls();
cassandraSettlements();
ryanNglProduction();
ryanNglExports();
jenniferFinResources();
jenniferRatingsMulti();
jenniferRatingsCross();
jenniferAbandonment();
